[package]
name = "FE"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = "1.0.218"
wasm-bindgen-futures = "0.4.50"